language: python
os:
  - linux
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install tox-travis
  - pip install codecov
script:
  - tox
  - ./check_version.py
after_success:
  - codecov
deploy:
  - provider: pypi
    user: ccoffrin
    password:
      secure: TCKv4HvEzMoba2g+IYa9pOBDxCnYSlB4URlMOFtICY5Q7srukrMc7SlczpLCJo7s634PlZEPr53MYIj7c0HOXUlM7WHQszfm4Sox8N1MSW+A2PI0xBkHtp5bVHHZtn4ZwFJBL7bAGePFVIjPYVZW2lXbZwu3BnqAfbyQPRv4Hm/AEV2sYUuEONWywxyxXOzAcKKR8CyOUaqOIO5cVvRDFz58fQ/dREnlXpj80HuGAM+KfiY0r/sp6BooOh4Bff8Pqz1LTEykOEQAPdo2LUKC6xnpHUU8Qpq8sYfaxCQ1OrO7WcxT6R/O2APAW+JkfT/PUaZWLYuRRNil+uNoVhgQfGoKO0xgLMwgcz5c0BdgSWc5D/5bFliD6cUcrz2bl4hwRcWOyxQtzWx/Aohyn+/wlnXCJ1k6cBi8+Pe/gOsm+EytsZ9h/OUiqdm/YpYp9EOiYk4vaudxuYE2vBLcXGJQdcSCbOosQ6UiV1pBKWRj6BRMJxKy9YJ3Yr8JZ3VY4vfjmejtHbEa0/SttGYPmqXIowUYmoIWYHnnE4BL2eQ7u3tANGG/NjddPTT86EFaFMHsk9sBX+hoIoFFMrfFZvTOqMP1EqQIVUh2Ez211j8DNPN23yXcdZDXmYkG2457y+2+ZGKeRd9YV9rev6gAK/7/mDy1tzP7UVpsO5MNrnzah34=
    on:
      tags: true
      branch: master
      condition: $TRAVIS_PYTHON_VERSION = '3.9'
